[package]
name = "bluest"
version = "0.1.0"
edition = "2021"
authors = ["Alex Moon"]
description = "Work in progress"
documentation = "https://docs.rs/bluest"
repository = "https://github.com/alexmoon/bluest/"
license = "BSD-2-Clause OR Apache-2.0"

[dependencies]
