[package]
name = "bluest"
version = "0.6.6"
authors = ["Alex Moon"]
edition = "2021"
description = "A cross-platform Bluetooth Low Energy (BLE) library"
documentation = "https://docs.rs/bluest"
repository = "https://github.com/alexmoon/bluest/"
license = "BSD-2-Clause OR Apache-2.0"
keywords = ["bluetooth", "BLE", "gatt", "bluez", "corebluetooth"]
categories = ["asynchronous", "hardware-support", "os"]

[package.metadata.docs.rs]
features = ["serde"]
default-target = "x86_64-apple-darwin"
targets = [
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]

[features]
serde = ["dep:serde", "uuid/serde", "bluer/serde"]
l2cap = ["dep:tokio", "bluer/l2cap", "dep:libc"]

[dependencies]
async-trait = "0.1.57"
futures-core = "0.3.28"
futures-lite = { version = "1.13.0", default-features = false }
serde = { version = "1.0.143", optional = true, features = ["derive"] }
tracing = { version = "0.1.36", default-features = false }

[dev-dependencies]
tokio = { version = "1.20.1", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "io-util",
] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
uuid = "1.1.1"

[target.'cfg(windows)'.dependencies]
futures-channel = "0.3.24"
windows = { version = "0.48.0", features = [
    "implement",
    "Foundation",
    "Foundation_Collections",
    "Devices_Enumeration",
    "Devices_Bluetooth",
    "Devices_Bluetooth_Advertisement",
    "Devices_Bluetooth_GenericAttributeProfile",
    "Devices_Radios",
    "Storage_Streams",
] }

[target.'cfg(target_os = "linux")'.dependencies]
bluer = { version = "0.16.1", features = ["bluetoothd"] }
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }

[target.'cfg(target_os = "android")'.dependencies]
java-spaghetti = "0.2.0"
async-channel = "2.2.0"
tokio = { version = "1.20.1", features = ["rt", "io-util"], optional = true }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
async-broadcast = "0.5.1"
libc = { version = "0.2", optional = true }
objc = { version = "0.2.8", package = "objc-rs" }
objc_id = "0.1.1"
objc-foundation = "0.1.1"
tokio = { version = "1.20.1", features = ["net"], optional = true }

[patch.crates-io]
objc_id = { path = "../rust-objc-id/" }
objc-foundation = { path = "../rust-objc-foundation/" }

[[example]]
name = "scan"
doc-scrape-examples = true

[[example]]
name = "l2cap_client"
required-features = ["l2cap"]
